[package]
name = "saidl"
version = "0.0.1"
edition = "2021"

[workspace]
members = [ "modules/*" ]

[dependencies]

# Local dependencies
saidl-helper = { path = "modules/saidl-helper" }
hls = { path = "modules/hls" }