[package]
name = "saidl-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { version = "1.2.1" }
reqwest = { version = "0.11.11" }
